version: '2'
services:
  sync:
    image: node:alpine
    entrypoint: /application/bin/torrdb-sync
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - COUCHDB=http://couchdb:5984/torrent
    volumes:
      - .:/application
    restart: always
  server:
    image: node:alpine
    entrypoint: /application/bin/torrdb-server
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - .:/application
    restart: always
    ports:
      - "3000:3000"
  couchdb:
    image: couchdb
    volumes:
      #- ./etc:/usr/local/etc/couchdb/local.d
      - ~/.torrdb/couchdb:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - 5601:5601
    restart: always
volumes:
  esdata:
    driver: local
