version: '2'
services:
  couchdb:
    image: couchdb
    volumes:
      #- ./etc:/usr/local/etc/couchdb/local.d
      - ~/.torrdb/couchdb:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - 5601:5601
volumes:
  esdata:
    driver: local
